import '../products/product.dart';
final List<Product> sampleProducts=[
  Product(
    id:'1',
    name: 'UCL Women Socks\n',
    price:549.99,
    image:'UCL_WOMEN_SOCKS.webp',
    isFav:false,
    categories: ['women','socks'],
    type:'women',
    inCart: false,
  ),
  Product(
      id:'2',
      name: 'UCL Women Shorts\n',
      price:849.99,
      image:'UCL_WOMEN_SHORTS.webp',
      isFav:false,
      categories: ['women','shorts'],
    type:'women',
    inCart: false,
  ),
  Product(
      id:'3',
      name: 'UCL Women Home Jersey',
      price:949.99,
      image:'UCL_WOMEN_HOME.webp',
      isFav:false,
      categories: ['women','jersey','home'],
    type:'women',
    inCart: false,
  ),
  Product(
      id:'5',
      name: 'UCL Men Third Kit Shorts',
      price:549.99,
      image:'UCL_MEN_THIRD_SHORTS.webp',
      isFav:false,
      categories: ['men','third','shorts'],
    type:'men',
    inCart: false,
  ),
  Product(
      id:'6',
      name: 'UCL Men Third Kit Jersey',
      price:1049.99,
      image:'UCL_MEN_THIRD.webp',
      isFav:false,
      categories: ['men','third','jersey','top'],
    type:'men',
    inCart: false,
  ),
  Product(
      id:'7',
      name: 'UCL Men Home Kit Socks',
      price:1049.99,
      image:'UCL_MEN_HOME_SOCKS.webp',
      isFav:false,
      categories: ['men','home','socks'],
    type:'men',
    inCart: false,
  ),
  Product(
      id:'8',
      name: 'UCL Men Home Kit Shorts',
      price:849.99,
      image:'UCL_MEN_HOME_SHORTS.webp',
      isFav:false,
      categories: ['men','home','shorts'],
    type:'men',
    inCart: false,
  ),
  Product(
      id:'10',
      name: 'UCL Men Home Kit Jersey',
      price:1149.99,
      image:'UCL_MEN_HOME.webp',
      isFav:false,
      categories: ['men','home','jersey','top'],
    type:'men',
    inCart: false,
  ),
  Product(
      id:'11',
      name: 'UCL Men Home Goalkeeper Kit Jersey',
      price:999.99,
      image:'UCL_MEN_GOALKEEPER.webp',
      isFav:false,
      categories: ['men','home','jersey','goalkeeper'],
    type:'men',
    inCart: false,
  ),
  Product(
      id:'12',
      name: 'UCL Men Away Kit Shorts',
      price:749.99,
      image:'UCL_MEN_AWAY_SHORTS.webp',
      isFav:false,
      categories: ['men','away','shorts'],
    type:'men',
    inCart: false,
  ),
  Product(
      id:'13',
      name: 'UCL Men Away Kit Jersey',
      price:1149.99,
      image:'UCL_MEN_AWAY.webp',
      isFav:false,
      categories: ['men','away','jersey','top'],
    type:'men',
    inCart: false,
  ),
  Product(
      id:'15',
      name: 'UCL Men Training Sweatshirt',
      price:649.99,
      image:'TRAINING_SWEATSHIRT.webp',
      isFav:false,
      categories: ['men','training','sweatshirt','home'],
    type:'training',
    inCart: false,
  ),
  Product(
      id:'16',
      name: 'UCL Men Training Pants Third Kit',
      price:549.99,
      image:'TRAINING_PANTS_THIRD.webp',
      isFav:false,
      categories: ['men','training','pants','third'],
    type:'training',
    inCart: false,
  ),
  Product(
      id:'17',
      name: 'UCL Men Training Pants',
      price:749.99,
      image:'TRAINING_PANTS.webp',
      isFav:false,
      categories: ['men','training','pants','home'],
    type:'training',
    inCart: false,
  ),
  Product(
      id:'18',
      name: 'UCL Men Training Sweatshirt Third Kit',
      price:699.99,
      image:'THIRD_SWEATSHIRT.webp',
      isFav:false,
      categories: ['men','training','sweatshirt','third','top'],
    type:'training',
    inCart: false,
  ),
];